base_images:
  fedora:
    name: fedora
    namespace: coreos
    tag: "33"
build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile
  inputs:
    fedora:
      as:
      - registry.svc.ci.openshift.org/coreos/fedora:33
  to: cosa46
promotion:
  excluded_images:
  - '*'
  name: "4.6"
  namespace: coreos
resources:
  '*':
    limits:
      devices.kubevirt.io/kvm: "1"
    requests:
      cpu: 1000m
      devices.kubevirt.io/kvm: "1"
      memory: 2Gi
tag_specification:
  name: "4.6"
  namespace: coreos
tests:
- as: sanity
  commands: coreos-assembler shell true
  container:
    from: cosa46
zz_generated_metadata:
  branch: rhcos-4.6
  org: coreos
  repo: coreos-assembler
